# Generated by Django 3.1.4 on 2020-12-28 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('nursury', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdetails',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nursury.plant'),
        ),
        migrations.AddField(
            model_name='cart',
            name='details',
            field=models.ManyToManyField(related_name='details', to='core.CartDetails'),
        ),
    ]
