# Generated by Django 3.1.4 on 2020-12-27 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='details',
            field=models.ManyToManyField(related_name='details', to='core.OrderDetails'),
        ),
        migrations.AlterField(
            model_name='order',
            name='placed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
