# Generated by Django 3.1.4 on 2020-12-27 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nursury', '0001_initial'),
        ('core', '0003_auto_20201228_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('Carted', models.BooleanField(default=False)),
                ('Carted_on', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='OrderDetails',
            new_name='CartDetails',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.AddField(
            model_name='cart',
            name='details',
            field=models.ManyToManyField(related_name='details', to='core.CartDetails'),
        ),
        migrations.AddField(
            model_name='cart',
            name='placed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
