# Generated by Django 3.1.4 on 2020-12-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201228_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='completed',
        ),
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('CART', 'CART'), ('ORDERED', 'ORDERED'), ('DELIVERED', 'DELIVERED')], default='CART', max_length=10),
        ),
    ]
