# Generated by Django 3.1.4 on 2020-12-28 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='plant_images/')),
                ('price', models.DecimalField(decimal_places=3, max_digits=19)),
            ],
        ),
    ]
